<<<<<<< Updated upstream
name: TypeScript
=======
name: Testing
>>>>>>> Stashed changes

on: [push, pull_request]

jobs:
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Fetching files
              uses: actions/checkout@v3
            - name: Installing Node
              uses: actions/setup-node@v3
            - name: Installing packages
              run: npm install
<<<<<<< Updated upstream
            - name: Checking for type errors
=======
            - name: Running tests
>>>>>>> Stashed changes
              run: npm run t
