name: Testing

on: [push, pull_request]

jobs:
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Fetching files
              uses: actions/checkout@v3
            - name: Installing Node
              uses: actions/setup-node@v3
            - name: Installing packages
              run: npm install
            - name: Running tests
              run: npm run t
