name: TypeScript

on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - name: Checking for type errors.
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
