name: TypeScript

on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checking for type errors.
      uses: fersilva16/ts-report-action@1.1.0
      with:
        project: ../tsconfig.json
